# Generated by Django 4.0.1 on 2022-12-13 14:24

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='UserData',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=50)),
                ('bithday', models.DateField(verbose_name='Дата рождения')),
                ('body_length', models.IntegerField(verbose_name='Длина тела(см)')),
                ('body_weight', models.IntegerField(verbose_name='Масса тела(кг)')),
                ('acromial_diameter', models.IntegerField(verbose_name='Акромиальный диаметр(мм)')),
                ('mid_chest_transverse_diameter', models.IntegerField(verbose_name='Среднегрудинный поперечный диаметр(мм)')),
                ('hip_width', models.IntegerField(verbose_name='Тазо-бедреный диаметр(ширина таза 1)(мм)')),
                ('interbody_diameter', models.IntegerField(verbose_name='Межвертельный диаметр(ширина таза 3)(мм)')),
                ('width_two_closed_knees', models.IntegerField(verbose_name='Ширина двух сомкнутых колен(мм)')),
                ('shin_circumference_minimal', models.IntegerField(verbose_name='Обхват голени минимальный(мм)')),
                ('forearm_circumference_minimal', models.IntegerField(verbose_name='Обхват предплечья минимальный(мм)')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL, verbose_name='Пользователь')),
            ],
        ),
    ]
