# Generated by Django 4.0.1 on 2022-06-11 15:59

from django.conf import settings
import django.contrib.auth.models
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('auth', '0012_alter_user_first_name_max_length'),
        ('morphologyApi', '0002_userdata_delete_user'),
    ]

    operations = [
        migrations.CreateModel(
            name='Users',
            fields=[
                ('user_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to=settings.AUTH_USER_MODEL)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'verbose_name': 'user',
                'verbose_name_plural': 'users',
                'abstract': False,
            },
            bases=('auth.user',),
            managers=[
                ('objects', django.contrib.auth.models.UserManager()),
            ],
        ),
        migrations.AlterField(
            model_name='userdata',
            name='acromial_diameter',
            field=models.IntegerField(verbose_name='Акромиальный диаметр(мм)'),
        ),
        migrations.AlterField(
            model_name='userdata',
            name='body_length',
            field=models.IntegerField(verbose_name='Длина тела(см)'),
        ),
        migrations.AlterField(
            model_name='userdata',
            name='body_weight',
            field=models.IntegerField(verbose_name='Масса тела(кг)'),
        ),
        migrations.AlterField(
            model_name='userdata',
            name='forearm_circumference_minimal',
            field=models.IntegerField(verbose_name='Обхват предплечья минимальный(мм)'),
        ),
        migrations.AlterField(
            model_name='userdata',
            name='hip_width',
            field=models.IntegerField(verbose_name='Тазо-бедреный диаметр(ширина таза 1)(мм)'),
        ),
        migrations.AlterField(
            model_name='userdata',
            name='interbody_diameter',
            field=models.IntegerField(verbose_name='Межвертельный диаметр(ширина таза 3)(мм)'),
        ),
        migrations.AlterField(
            model_name='userdata',
            name='mid_chest_transverse_diameter',
            field=models.IntegerField(verbose_name='Среднегрудинный поперечный диаметр(мм)'),
        ),
        migrations.AlterField(
            model_name='userdata',
            name='shin_circumference_minimal',
            field=models.IntegerField(verbose_name='Обхват голени минимальный(мм)'),
        ),
        migrations.AlterField(
            model_name='userdata',
            name='width_two_closed_knees',
            field=models.IntegerField(verbose_name='Ширина двух сомкнутых колен(мм)'),
        ),
        migrations.AlterField(
            model_name='userdata',
            name='user_id',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='morphologyApi.users'),
        ),
    ]
