# Generated by Django 4.0.1 on 2022-06-11 16:34

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('morphologyApi', '0003_users_alter_userdata_acromial_diameter_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='userdata',
            name='user_id',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
        migrations.DeleteModel(
            name='Users',
        ),
    ]
