# Generated by Django 4.0.1 on 2022-06-11 16:49

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('morphologyApi', '0004_alter_userdata_user_id_delete_users'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='userdata',
            name='user_id',
        ),
    ]
