# Generated by Django 4.0.1 on 2022-06-11 17:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('morphologyApi', '0006_users_userdata_user_id'),
    ]

    operations = [
        migrations.AlterField(
            model_name='userdata',
            name='bithday',
            field=models.DateField(verbose_name='Дата рождения'),
        ),
    ]
