# Generated by Django 4.0.1 on 2022-06-11 17:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('morphologyApi', '0007_alter_userdata_bithday'),
    ]

    operations = [
        migrations.AddField(
            model_name='users',
            name='password',
            field=models.CharField(max_length=10, null=True),
        ),
    ]
