GET http://127.0.0.1:8000/api/users
###
POST http://127.0.0.1:8000/api/users/
Content-type: application/json

{
    "name": "user",
    "email": "user@user.com"
}
###

DELETE http://127.0.0.1:8000/api/users/1/

